name: Test
on: push
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Deno
        uses: denolib/setup-deno@master

      - name: Run tests
        run: deno test --allow-read=input
